# Generated by Django 2.1.4 on 2018-12-16 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
