# Generated by Django 2.1.3 on 2019-02-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importexport', '0003_auto_20181230_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='keywords',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='profile',
            field=models.IntegerField(blank=True, choices=[(1, 'lorenzo.writing'), (2, 'benni.wolf09'), (3, 'martina.dresdner'), (4, 'linda-welle')], null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='status',
            field=models.IntegerField(choices=[(0, 'processing'), (1, 'queued'), (2, 'error'), (3, 'accepted'), (99, 'cancelled')], default=0),
        ),
    ]
